### PR TITLE
Changes for final submission

### PR DESCRIPTION
**Pull request by rcurtin**
Here are some suggestions for some final changes.

### CODE REVIEW

**Comment by conradsnicta** [comment]
Looks good to me.  Does the extra text cause any cascading layout issues?  If I recall correctly, we were close to running out of room, which often means that the layout of the paper is in a critical state.

**Comment by conradsnicta** [comment]
I just checked out your 'final' branch, and the layout looks all okay even with the extra text.

**Comment by rcurtin** [comment]
Yep, the `as such` -> `thus` change was to fix the layout---the three fewer characters caused the last word in that paragraph to not wrap, leaving enough space for the added text. :)

**Comment by zoq** [comment]
Looks good to me as well.

**Pull request merged**
